### ISSUE TITLE
Use with qb-inventory?

### ISSUE THREAD

**Issue by Terp11** [xViperAG/qb-newsjob#2]
any way to use with qb-inventory?

**Comment by xViperAG** [comment]
No. The only way to use qb-inventory is if you implement it yourself, which is not that hard to do. I've moved towards using ox_resources going forward for all of my resources for performance and enhancement.

Will it be added in? No. As it's open sourced, it allows for the user to change the script to their liking. My paid scripts, however, will receive the treatment of getting qb-inventory.
